# Generated by Django 6.1.1 on 2026-09-30 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedTime',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Band vaqt', max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_times', to='marketplace.business')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_times', to='marketplace.staff')),
            ],
            options={
                'db_table': 'blocked_times',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('booking_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=32)),
                ('booking_date', models.DateField(db_index=True)),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('total_price_uzs', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('CONFIRMED', 'Tasdiqlangan'), ('IN_PROGRESS', 'Jarayonda'), ('COMPLETED', 'Bajarildi'), ('CANCELLED', 'Bekor qilindi'), ('NO_SHOW', 'Kelgani yo‘q')], db_index=True, default='CONFIRMED', max_length=32)),
                ('cancel_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='marketplace.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bookings', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='marketplace.service')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='marketplace.staff')),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-booking_date', '-start_time'],
            },
        ),
    ]
