# Generated by Django 6.1.1 on 2026-09-30 20:18

from django.conf import settings
from django.db import migrations, models

ACTIVE = ('PENDING', 'CONFIRMED', 'IN_PROGRESS')


def cancel_duplicate_active_bookings(apps, schema_editor):
    """Keep the earliest active booking per (staff, date, start_time); cancel the rest."""
    Booking = apps.get_model('bookings', 'Booking')
    seen = set()
    qs = Booking.objects.filter(status__in=ACTIVE, staff__isnull=False).order_by('created_at', 'id')
    for booking in qs.iterator():
        key = (booking.staff_id, booking.booking_date, booking.start_time)
        if key in seen:
            booking.status = 'CANCELLED'
            booking.cancel_reason = 'Tizim: ikki marta band qilingan vaqt (avtomatik bekor qilindi).'
            booking.save(update_fields=['status', 'cancel_reason'])
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(cancel_duplicate_active_bookings, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'CONFIRMED', 'IN_PROGRESS'])), fields=('staff', 'booking_date', 'start_time'), name='uniq_active_booking_per_staff_slot'),
        ),
    ]
