# Generated by Django 6.1.1 on 2026-09-30 22:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_reminder_sent_and_more'),
        ('marketplace', '0003_business_hours_js_weekday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('staff__isnull', True), ('status__in', ['PENDING', 'CONFIRMED', 'IN_PROGRESS'])), fields=('business', 'booking_date', 'start_time'), name='uniq_active_booking_per_business_slot_no_staff'),
        ),
    ]
