# Generated by Django 6.1.1 on 2026-09-30 20:34

from django.db import migrations, models


def python_to_js_weekday(apps, schema_editor):
    """Stored rows used Python's weekday() (0=Monday); the frontend uses JS getDay() (0=Sunday)."""
    BusinessHours = apps.get_model('marketplace', 'BusinessHours')
    # Two passes to stay clear of the (business, day_of_week) unique constraint.
    for row in BusinessHours.objects.all():
        BusinessHours.objects.filter(pk=row.pk).update(day_of_week=row.day_of_week + 100)
    for row in BusinessHours.objects.all():
        BusinessHours.objects.filter(pk=row.pk).update(day_of_week=(row.day_of_week - 100 + 1) % 7)


def js_to_python_weekday(apps, schema_editor):
    BusinessHours = apps.get_model('marketplace', 'BusinessHours')
    for row in BusinessHours.objects.all():
        BusinessHours.objects.filter(pk=row.pk).update(day_of_week=row.day_of_week + 100)
    for row in BusinessHours.objects.all():
        BusinessHours.objects.filter(pk=row.pk).update(day_of_week=(row.day_of_week - 100 + 6) % 7)


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_business_is_trial_business_partner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshours',
            name='day_of_week',
            field=models.IntegerField(help_text='0=Yakshanba (Sunday) ... 6=Shanba (Saturday)'),
        ),
        migrations.RunPython(python_to_js_weekday, js_to_python_weekday),
    ]
