# Generated by Django 6.1.1 on 2026-10-01 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_business_hours_js_weekday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessApplication',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('telegram_chat_id', models.CharField(db_index=True, max_length=64)),
                ('telegram_user_id', models.CharField(blank=True, max_length=64)),
                ('telegram_username', models.CharField(blank=True, max_length=128)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(blank=True, max_length=128)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Qoralama'), ('PENDING', 'Kutilmoqda'), ('APPROVED', 'Tasdiqlangan'), ('REJECTED', 'Rad etilgan')], db_index=True, default='DRAFT', max_length=16)),
                ('step', models.CharField(choices=[('ASK_NAME', 'Nomi'), ('ASK_CATEGORY', 'Kategoriya'), ('ASK_CITY', 'Shahar'), ('ASK_DISTRICT', 'Tuman'), ('ASK_ADDRESS', 'Manzil'), ('ASK_PHONE', 'Telefon'), ('ASK_HOURS', 'Ish vaqti'), ('ASK_DESCRIPTION', 'Tavsif'), ('ASK_PHOTOS', 'Rasmlar'), ('CONFIRM', 'Tasdiqlash'), ('DONE', 'Tugallandi')], default='ASK_NAME', max_length=24)),
                ('awaiting_reject_from', models.CharField(blank=True, default='', max_length=64)),
                ('reject_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_applications', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.city')),
                ('resulting_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_application', to='marketplace.business')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_business_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessApplicationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='business_applications/%Y/%m/')),
                ('telegram_file_id', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='marketplace.businessapplication')),
            ],
            options={
                'db_table': 'business_application_photos',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessApplicationHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(help_text='0=Yakshanba (Sunday) ... 6=Shanba (Saturday)')),
                ('open_time', models.CharField(default='09:00', max_length=10)),
                ('close_time', models.CharField(default='18:00', max_length=10)),
                ('is_closed', models.BooleanField(default=False)),
                ('break_start', models.CharField(blank=True, default='', max_length=10)),
                ('break_end', models.CharField(blank=True, default='', max_length=10)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='marketplace.businessapplication')),
            ],
            options={
                'db_table': 'business_application_hours',
                'ordering': ['day_of_week'],
                'unique_together': {('application', 'day_of_week')},
            },
        ),
    ]
