# Generated by Django 6.1.1 on 2026-09-30 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(blank=True, max_length=32)),
                ('queue_number', models.CharField(db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('WAITING', 'Kutilmoqda'), ('CALLED', 'Chaqirildi'), ('SERVING', 'Xizmat ko‘rsatilmoqda'), ('COMPLETED', 'Yakunlandi'), ('SKIPPED', 'O‘tkazib yuborildi'), ('NO_SHOW', 'Kelgani yo‘q')], db_index=True, default='WAITING', max_length=32)),
                ('estimated_wait_minutes', models.IntegerField(default=15)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='marketplace.business')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to='marketplace.service')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to='marketplace.staff')),
            ],
            options={
                'db_table': 'queue_entries',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueueAuditLog',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_audits', to='marketplace.business')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='queues.queueentry')),
            ],
            options={
                'db_table': 'queue_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingQueueAction',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('status', models.CharField(default='PENDING', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.business')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('called_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_called', to='queues.queueentry')),
                ('current_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_current', to='queues.queueentry')),
            ],
            options={
                'db_table': 'pending_queue_actions',
            },
        ),
    ]
