# Generated by Django 6.1.1 on 2026-09-30 20:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
import re

NUMBER_RE = re.compile(r'(\d+)$')


def _num(value):
    match = NUMBER_RE.search(value or '')
    return int(match.group(1)) if match else 0


def backfill_queue_dates(apps, schema_editor):
    from django.utils import timezone

    QueueEntry = apps.get_model('queues', 'QueueEntry')
    QueueDailyCounter = apps.get_model('queues', 'QueueDailyCounter')
    groups = {}
    for entry in QueueEntry.objects.order_by('created_at', 'id').iterator():
        day = timezone.localtime(entry.created_at).date() if entry.created_at else timezone.localdate()
        key = (entry.business_id, day)
        used = groups.setdefault(key, set())
        number = entry.queue_number
        if not number or number in used:
            candidate = max((_num(n) for n in used), default=0) + 1
            number = f'A{candidate:03d}'
        used.add(number)
        QueueEntry.objects.filter(pk=entry.pk).update(queue_date=day, queue_number=number)
    for (business_id, day), numbers in groups.items():
        QueueDailyCounter.objects.update_or_create(
            business_id=business_id, date=day, defaults={'last_number': max((_num(n) for n in numbers), default=0)}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_business_is_trial_business_partner_and_more'),
        ('queues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueDailyCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'queue_daily_counters',
            },
        ),
        migrations.AddField(
            model_name='pendingqueueaction',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingqueueaction',
            name='source',
            field=models.CharField(default='WEB', max_length=16),
        ),
        migrations.AddField(
            model_name='pendingqueueaction',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='queue_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='pendingqueueaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('CONFIRMED', 'Tasdiqlandi'), ('CANCELLED', 'Bekor qilindi'), ('EXPIRED', 'Muddati o‘tdi')], default='PENDING', max_length=32),
        ),
        migrations.AddField(
            model_name='queuedailycounter',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_counters', to='marketplace.business'),
        ),
        migrations.RunPython(backfill_queue_dates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.UniqueConstraint(fields=('business', 'queue_date', 'queue_number'), name='uniq_queue_number_per_business_day'),
        ),
        migrations.AddConstraint(
            model_name='queuedailycounter',
            constraint=models.UniqueConstraint(fields=('business', 'date'), name='uniq_queue_counter_per_business_day'),
        ),
    ]
