# Generated by Django 6.1.1 on 2026-09-30 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='F.I.SH')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Elektron pochta')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='Telefon')),
                ('role', models.CharField(choices=[('FOUNDER', 'Founder'), ('ADMIN', 'Admin'), ('OPERATING_PARTNER', 'Operating Partner'), ('SALES_MANAGER', 'Sales Manager'), ('BUSINESS_MANAGER', 'Business Manager'), ('SUPPORT', 'Support'), ('BUSINESS_OWNER', 'Business Owner'), ('STAFF', 'Staff'), ('EMPLOYEE', 'Employee'), ('CUSTOMER', 'Customer')], db_index=True, default='CUSTOMER', max_length=32, verbose_name='Rol')),
                ('status', models.CharField(choices=[('ACTIVE', 'Faol'), ('SUSPENDED', 'To‘xtatilgan'), ('PENDING_VERIFICATION', 'Tasdiqlash kutilmoqda')], db_index=True, default='ACTIVE', max_length=32, verbose_name='Holat')),
                ('telegram_chat_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=128, null=True)),
                ('telegram_notifications_enabled', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramAuthSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('code', models.CharField(db_index=True, max_length=16)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telegram_auth_sessions',
            },
        ),
        migrations.CreateModel(
            name='TelegramLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telegram_link_tokens',
            },
        ),
    ]
