# Generated by Django 6.1.1 on 2026-09-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramauthsession',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramauthsession',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
