# Generated by Django 6.1.1 on 2026-09-30 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('price_uzs', models.IntegerField(default=0)),
                ('max_staff', models.IntegerField(default=1)),
                ('max_monthly_bookings', models.IntegerField(default=50)),
                ('features_json', models.TextField(default='[]')),
            ],
            options={
                'db_table': 'subscription_plans',
            },
        ),
        migrations.CreateModel(
            name='AdPromotion',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('banner_url', models.URLField(blank=True, max_length=500)),
                ('link_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='marketplace.business')),
            ],
            options={
                'db_table': 'ad_promotions',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTransaction',
            fields=[
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('plan_code', models.CharField(max_length=32)),
                ('amount_uzs', models.IntegerField(default=0)),
                ('months', models.IntegerField(default=1)),
                ('status', models.CharField(default='PENDING', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_txs', to='marketplace.business')),
            ],
            options={
                'db_table': 'subscription_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
