# Generated by Django 6.1.1 on 2026-09-30 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adpromotion',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adpromotion',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adpromotion',
            name='impressions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adpromotion',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='adpromotion',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adpromotion',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=16),
        ),
        migrations.AddField(
            model_name='adpromotion',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adpromotion',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='subscriptions.subscriptiontransaction'),
        ),
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='kind',
            field=models.CharField(choices=[('SUBSCRIPTION', 'Obuna'), ('PROMOTION', 'Reklama')], default='SUBSCRIPTION', max_length=16),
        ),
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='payment_method',
            field=models.CharField(default='TELEGRAM', max_length=32),
        ),
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscriptiontransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('CONFIRMED', 'Tasdiqlandi'), ('CANCELLED', 'Bekor qilindi')], default='PENDING', max_length=32),
        ),
    ]
