# Generated by Django 6.1.1 on 2026-09-30 20:18

import django.db.models.deletion
from django.db import migrations, models

LEGACY_STAGE_MAP = {'NEW': 'LEAD', 'MEETING': 'DEMO', 'AGREEMENT': 'TRIAL', 'WON': 'ACTIVE', 'LOST': 'CHURNED'}


def migrate_legacy_partner_data(apps, schema_editor):
    CRMLead = apps.get_model('partners', 'CRMLead')
    for old, new in LEGACY_STAGE_MAP.items():
        CRMLead.objects.filter(status=old).update(status=new)
    PartnerCommission = apps.get_model('partners', 'PartnerCommission')
    PartnerCommission.objects.filter(status='SETTLED').update(status='PAID')
    for comm in PartnerCommission.objects.filter(total_amount_uzs=0).iterator():
        rate = comm.partner_rate or 0.30
        total = int(round(comm.amount_uzs / rate)) if rate else comm.amount_uzs
        comm.total_amount_uzs = total
        comm.navbatbor_share_uzs = total - comm.amount_uzs
        comm.plan_code = comm.plan_code or comm.business.subscription_plan_code
        comm.save(update_fields=['total_amount_uzs', 'navbatbor_share_uzs', 'plan_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_business_is_trial_business_partner_and_more'),
        ('partners', '0001_initial'),
        ('subscriptions', '0002_adpromotion_clicks_adpromotion_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmlead',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='crmlead',
            name='converted_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_leads', to='marketplace.business'),
        ),
        migrations.AddField(
            model_name='crmlead',
            name='deal_value_uzs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crmlead',
            name='last_contact_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crmlead',
            name='next_contact_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crmlead',
            name='telegram_username',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='crmlead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='partnercommission',
            name='navbatbor_share_uzs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partnercommission',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnercommission',
            name='partner_rate',
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name='partnercommission',
            name='plan_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='partnercommission',
            name='total_amount_uzs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partnercommission',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='subscriptions.subscriptiontransaction'),
        ),
        migrations.AddField(
            model_name='partnerreport',
            name='issues_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='partnerreport',
            name='new_businesses_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partnerreport',
            name='new_customers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partnerreport',
            name='next_week_plan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='partnerreport',
            name='partner_commission_uzs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partnerreport',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerreport',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerreport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerreport',
            name='status',
            field=models.CharField(default='SUBMITTED', max_length=16),
        ),
        migrations.AddField(
            model_name='partnerreport',
            name='telegram_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerreport',
            name='total_businesses_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partnerreport',
            name='total_revenue_uzs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crmlead',
            name='status',
            field=models.CharField(choices=[('LEAD', 'Yangi lead'), ('CONTACTED', 'Aloqaga chiqildi'), ('DEMO', 'Demo'), ('TRIAL', 'Sinov'), ('PAID', 'To‘lov qilgan'), ('ACTIVE', 'Faol mijoz'), ('CHURNED', 'Ketgan')], default='LEAD', max_length=32),
        ),
        migrations.RunPython(migrate_legacy_partner_data, migrations.RunPython.noop),
    ]
